version: "2.0"

services:
  blockchain_investigation_gateway:
    image: nginx:latest
    container_name: blockchain_investigation_gateway
    restart: always
    volumes:
      - ./gateway/nginx_config.conf:/etc/nginx/conf.d/default.conf
    networks:
      - private-network
    env_file:
      - ../envs/gateway.env
    ports:
      - 84:80
    expose:
      - 80
    depends_on:
      - blockchain_investigation_implementation
    
  blockchain_investigation_implementation:
    image: sebastq/blockchain-investigation:implementation.v0.1.0
    container_name: blockchain_investigation_implementation
    restart: always
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000
    volumes:
      - ../shared/implementation:/app/app/api/shared
    env_file:
      - ../envs/implementation.env
    networks:
      - private-network

networks:
  private-network:
    driver: bridge